---
- name: Backup of cisco and eos devices
  hosts: cisco,eos
  gather_facts: false
  tasks:
  - name: Backup of the cisco device
    when: ansible_network_os == 'cisco.ios.ios'
    cisco.ios.ios_config:
      backup: yes
    register: backup_ios_location

  - name: Backup of the eos device
    when: ansible_network_os == 'arista.eos.eos'
    arista.eos.eos_config:
      backup: yes
    register: backup_eos_location

  - name: Create the directory
    ansible.builtin.file:
      path: "/home/student/net_backups"
      state: directory
      recurse: true
    delegate_to: workstation.lab.example.com

  - name: Save the cisco backup
    ansible.builtin.lineinfile:
      line: "{{ backup_ios_location.backup_path }}"
      path: "/home/student/net_backups/{{ inventory_hostname }}.txt"
      state: present
      create: yes
    when: ansible_network_os == 'cisco.ios.ios'
    delegate_to: workstation.lab.example.com

  - name: Save the eos backup
    ansible.builtin.lineinfile:
      line: "{{ backup_eos_location.backup_path }}"
      path: "/home/student/net_backups/{{ inventory_hostname }}.txt"
      state: present
      create: yes
    when: ansible_network_os == 'arista.eos.eos'
    delegate_to: workstation.lab.example.com
...
